import { StyleSheet } from 'react-native';

const tabSheetColor = 'rgba(255, 255, 255, 0.5)';
const mainTextColor = '#FFDB21';
const secondaryTextColor = 'black';

export const styleSheets = StyleSheet.create({
    background: {
        flex: 1,
        justifyContent: 'center',
    },
    logo: {
        alignItems: 'center',
        justifyContent: 'center',
        flex: 1,
    },
    name: {
        fontSize: 70,
        textDecorationLine: 'underline',
        color: mainTextColor,
        fontFamily: 'oswald-bold',
        marginTop: 40,
    },
    screenName: {
        fontSize: 60,
        marginTop: 10,
    },
    business: {
        fontSize: 50,
        top: '70%',
        fontFamily: 'oswald-regular',
        color: 'white',
        textShadowColor: 'grey',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 4,
    },
    slogan: {
        fontSize: 18,
        color: secondaryTextColor,
    },
    filler: {
        flex: 1,
    },
    keyboardAvoidingView: {
        flex: 2,
        alignItems: 'center',
        justifyContent: 'center',
        width: '100%',
    },
    inner: {
        flex: 1,
        justifyContent: 'center',
    },
    input: {
        width: 250,
        height: 50,
        margin: 5,
        backgroundColor: tabSheetColor,
        borderWidth: 1,
        borderRadius: 50,
        textAlign: 'center',
        fontSize: 20,
    },
    invalid: {
        flex: 1,
        backgroundColor: 'red',
    },
    touchableHighlight: {
        width: 250,
        height: 50,
        backgroundColor: mainTextColor,
        alignSelf: 'center',
        borderColor: secondaryTextColor,
        margin: 5,
        borderWidth: 1.5,
        borderRadius: 50,
        justifyContent: 'center',
    },
    touchableHighlightDark: {
        width: 250,
        height: 50,
        backgroundColor: secondaryTextColor,
        alignSelf: 'center',
        borderColor: mainTextColor,
        margin: 5,
        borderWidth: 3,
        borderRadius: 50,
        justifyContent: 'center',
    },
    touchableHighlightText: {
        textAlign: 'center',
        fontSize: 22,
        fontFamily: 'oswald-bold',
        color: 'white',
        textShadowColor: 'grey',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
        //color: secondaryTextColor,
    },
    touchableHighlightTextLight: {
        textAlign: 'center',
        color: mainTextColor,
        fontSize: 20,
    },
    tabSheet: {
        flex: 5,
        backgroundColor: tabSheetColor,
        height: '70%',
        width: '80%',
        alignSelf: 'center',
        alignItems: 'center',
    },
    tabSheetHeader: {
        fontSize: 30,
        margin: 10,
        //textDecorationLine: 'underline',
        textTransform: 'uppercase',
        color: secondaryTextColor,
        opacity: 1,
        fontFamily: 'oswald-regular',
        textShadowColor: 'grey',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 4,
    },
    qrSheet: {
        flex: 5,
        height: '70%',
        alignSelf: 'center',
        alignItems: 'center',
    },
    qrCode: {
        marginTop: 500,
    },
    valid: {
        flex: 1,
        backgroundColor: 'green',
    },
    validView: {
        height: '100%',
        width: '100%',
        backgroundColor: 0.8,
    },
    vardguiden: {
        height: 200,
        width: 200,
        margin: 50,
    },
    safe: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    qr: {
        flex: 1,
        borderRadius: 20,
        backgroundColor: 'yellow',
    },
    scanner: {
        flex: 1,
    },
    scannerView: {
        flex: 5,
    },
    cancelButtonView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'flex-end',
    },
    touchableValid: {
        width: '100%',
        height: '100%',
    },
    certButton: {
        width: 20,
        height: 20,
        backgroundColor: 'pink',
        alignSelf: 'center',
        borderColor: secondaryTextColor,
        margin: 5,
        borderWidth: 1,
        borderRadius: 50,
        justifyContent: 'center',
    },
    container: {
        flex: 1,
        width: '100%',
        shadowOffset: { width: 2, height: 2 },
        shadowColor: 'grey',
        shadowOpacity: 0.5,
    },
    scrollItem: {
        flex: 1,
        marginHorizontal: 10,
        marginTop: 10,
        padding: 20,
        backgroundColor: 'white',
        borderWidth: 1,
        borderColor: 'white',
        borderRadius: 5,
        fontSize: 20,
    },
    text: {
        fontSize: 20,
        color: 'black',
    },
    vaccinated: {
        backgroundColor: '#FFE871',
        width: '90%',
        height: 56,
        marginTop: 20,
        borderRadius: 10,
        justifyContent: 'center',
    },
    vaccinatedText: {
        fontSize: 20,
        alignSelf: 'center',
    },
    vaccInfo: {
        fontSize: 20,
        color: 'black',
        padding: 10,
        margin: 5,
    },
});
